my_search = {
    "BlockRobot: Increasing Privacy in Human Robot Interaction by Using Blockchain.",
    "\"I Don't Want Parents to Watch My Lessons\" - Privacy Trade-offs in the Use of Telepresence Robots in Schools for Children with Long-term Illnesses.",
    "Towards Privacy-friendly Telepresence Robots for Schoolchildren with Long-term Illnesses - User Needs of Relevant User Groups.",
    "AI privacy preserving robots working in a smart sensor environment.",
    "Privacy-Sensitive Robotics: Perceptions, Measures, and Metrics.",
    "User Feedback on Physical Marker Interfaces for Protecting Visual Privacy from Mobile Robots.",
    "Navigating the Human-Robot Interaction Landscape. Practical Guidelines for Privacy-Conscious Social Robots.",
    "Social Robots in Healthcare: Characterizing Privacy Considerations.",
    "Protecting User Data Through Privacy-Sensitive Robot Design.",
    "Understanding users' perception of privacy in human-robot interaction.",
    "How do People Perceive Privacy and Interaction Quality while Chatting with a Crowd-operated Robot?",
    "Surveying Adult Perceptions of Privacy and Attitudes towards Social Robots in the Home.",
    "Morphological gender recognition by a social robot and privacy concerns: late breaking reports.",
    "The effect of monitoring by cameras and robots on the privacy enhancing behaviors of older adults.",
    "Be More Transparent and Users Will Like You: A Robot Privacy and User Experience Design Experiment.",
    "Privacy Aware Robotics.",
    "Privacy-Sensitive Robotics.",
    "Contextual Understanding of Teen & Youth Privacy Perceptions with Social Robots.",
    "Framing Effects on Privacy Concerns about a Home Telepresence Robot.",
    "Effective Engineering, Stakeholder Involvement, and Regulatory Plurality Within Privacy-Aware Robotics.",
    "Privacy and Telepresence Robotics: What do Non-scientists Think?",
    "Snitches Get Unplugged: Adolescents' Privacy Concerns about Robots in the Home are Relationally Situated.",
    "PriMA-Care: Privacy-Preserving Multi-modal Dataset for Human Activity Recognition in Care Robots.",
    "CONFIDANT: A Privacy Controller for Social Robots.",
    "The Privacy-Utility Tradeoff for Remotely Teleoperated Robots.",
    "Privacy-Preserving and Auditable Federated Deep Reinforcement Learning for Robotic Manipulation.",
    "RoboCode-Ethicists: Privacy-friendly robots, an ethical responsibility of engineers?",
    "\"They See You're a Girl if You Pick a Pink Robot with a Skirt\": A Qualitative Study of How Children Conceptualize Data Processing and Digital Privacy Risks.",
    "Designing for In-Home Long-Term Family-Robot Interactions: Family Preferences, Connection-Making, and Privacy.",
    "Investigating Limits and Effectiveness of Privacy Conversations: the Case of Service Robots in an Office Environment.",
    "Robotic Society: Privacy as a Legal and Technological Issue.",
    "Exploring Privacy Concerns, Privacy Risks and Benefits on Users' Trust and Engagement in Continual Use of Service Robots.",
    "Privacy Behavior of the Elderly toward Caregiver Robots.",
    "Enhancing Privacy in Robotics via Judicious Sensor Selection.",
    "Obscuring Objectives with Pareto-Optimal Privacy-Aware Trajectories in Multi-Robot Coverage.",
    "Coordinated multi-robot planning while preserving individual privacy.",
    "Privacy Risks in Reinforcement Learning for Household Robots.",
    "Your Robot Might Be Inadvertently or Deliberately Spying on You: A Critical Analysis of Privacy Practices in the Robotics Industry.",
    "Privacy-Preserving Multi-Robot Task Allocation via Secure Multi-Party Computation.",
    "Investigating the Privacy Risk of Using Robot Vacuum Cleaners in Smart Environments.",
    "RoboCode-Ethicists: Privacy-friendly robots, an ethical responsibility of engineers?",
    "Designing a System Based on Robotic Assistance for Privacy Awareness in Smart Environments.",
    "Understanding Worker Perceptions Toward Privacy When Working with Collaborative Robots That Provide As-Needed Assistance.",
    "Consumer-Friendly Methods for Privacy Protection Against Cleaning Robots.",
    "Privacy at Home: An Inquiry into Sensors and Robots for the Stay at Home Elderly.",
    "Information Security, Privacy, and Trust in Social Robotic Assistants for Older Adults.",
    "Social Robots, Privacy, and Ownership of Data: Some Problems and Suggestions.",
    "Called Back Onstage: Dramaturgic Analysis, Domestic Social Robots, and Privacy.",
    "Analyzing Security & Privacy (S&P) Labels For AI Integrated Social Robots: A Novel User Assessment Based Research Study.",
    "Are You Watching Me? A Study on Privacy Notice Design of Social Robot.",
    "Designing and Validating a Blockchain-based Architecture to Enforce Privacy in Human Robot Interaction.",
    "A Macroscopic Privacy Model for Heterogeneous Robot Swarms.",
    "Do Privacy Concerns Prevent Employees' Acceptance of Smart Wearables and Collaborative Robots?",
    "Examining Diverse Gender Dynamics in Human-Robot Interaction: Trust Privacy and Safety Perceptions.",
    "A Qualitative Observational Video-Based Study on Perceived Privacy in Social Robots' Based on Robots Appearances.",
    "Themes and Research Directions in Privacy-Sensitive Robotics.",
    "A Privacy Filter Framework for Internet of Robotic Things Applications.",
    "Privacy-Preserving User Pose Prediction for Safe and Efficient Human-Robot Interaction.",
    "Detection of privacy-sensitive situations for social robots in smart homes.",
    "The Robot Who Knew Too Much: Toward Understanding the Privacy/Personalization Trade-Off in Child-Robot Conversation.",
    "Privacy and Socially Assistive Robots - A Meta Study.",
    "Trust-Driven Privacy in Human-Robot Interactions.",
    "A spotlight on security and privacy risks with future household robots: attacks and lessons.",
    "Privacy Communication Patterns for Domestic Robots.",
    "Beyond Data Collection: Safeguarding User Privacy in Social Robotics.",
    "Artificial Empathy for Clinical Companion Robots with Privacy-By-Design.",
    "Public Perception, Privacy, Safety, and Ethical Considerations of Communication Robots in Law Enforcement.",
    "Evaluation of physical marker interfaces for protecting visual privacy from mobile robots.",
    "Tolerating Untrustworthy Robots: Studying Human Vulnerability Experience within a Privacy Scenario for Trust in Robots.",
    "Privacy First: Designing Responsible and Inclusive Social Robot Applications for in the Wild Studies.",
    "Investigating Privacy in the Context of Office Delivery Robots.",
    "Evaluating People's Perception of Trust and Privacy based on Robot's Appearance.",
    "Ethical Design for Privacy-related Communication in Human-Robot Interaction.",
    "Comparative Analysis of Vision-Based Sensors for Human Monitoring in Care Robots: Exploring the Utility-Privacy Trade-off.",
    "Towards Designing Privacy-Compliant Social Robots for Use in Private Households: A Use Case Based Identification of Privacy Implications and Potential Technical Measures for Mitigation.",
    "Issues of privacy and electronic personhood in robotics.",
    "Performing Human Shadow Detection for Camera-Based Privacy-Preserving Human-Robot Interactions.",
    "A focus group study of privacy concerns about telepresence robots.",
    "Walking Away from the Robot: Negotiating Privacy with a Robot.",
    "Navigating Privacy Patterns in the Era of Robotaxis.",
    "Securing the Future: Exploring Privacy Risks and Security Questions in Robotic Systems.",
    "Social Robots in Care and Data Privacy - A European Perspective.",
    "Privacy-Preserving Robot Vision with Anonymized Faces by Extreme Low Resolution.",
    "Robots as AI Double Agents: Privacy in Motion Planning.",
    "BRNES: Enabling Security and Privacy-Aware Experience Sharing in Multiagent Robotic and Autonomous Systems.",
    "Privacy and security challenges for autonomous agents : A study of two social humanoid service robots.",
    "Towards A Unique User-Centric Security & Privacy (S&P) Label For Social Robots.",
    "\"Socially Assistive Robot Privacy Model\": A Multi-model Approach to Evaluating Socially Assistive Robot Privacy Concerns.",
    "Embodiment, Privacy and Social Robots: May I Remember You?",
    "Privacy Concerns in Robot Teleoperation: Does Personality Influence What Should Be Hidden?",
    "A Telepresence Robot in Residential Care: Family Increasingly Present, Personnel Worried About Privacy.",
    "Privacy-Secure HRI: Framework of Human-Robot Interaction Protecting User's Privacy.",
    "Co-Learning around Social Robots with School Pupils and University Students - Focus on Data Privacy Considerations.",
    "Understanding Privacy-friendly Design of Robot Eyes.",
    "A Survey on Privacy Attacks Against Digital Twin Systems in AI-Robotics.",
    "Usage Intention of Social Robots for Domestic Purpose: From Security, Privacy, and Legal Perspectives.",
    "Data Privacy Preserving for Centralized Robotic Fault Diagnosis With Modified Dataset Distillation.",
    "Influence of the Privacy Issue in the Deployment and Design of Networking Robots in European Urban Areas.",
    "Never Trust Anything That Can Think for Itself, if You Can't Control Its Privacy Settings: The Influence of a Robot's Privacy Settings on Users' Attitudes and Willingness to Self-disclose.",
    "Effects of Privacy Warning on the Intention to Disclose Personal Information During Interaction with a Robot in Public Spaces.",
    "Effects of Social Behaviors of Robots in Privacy-Sensitive Situations.",
    "Designing Commercial Therapeutic Robots for Privacy Preserving Systems and Ethical Research Practices Within the Home.",
    "Is the Robot Spying on me? A Study on Perceived Privacy in Telepresence Scenarios in a Care Setting with Mobile and Humanoid Robots.",
    "Our business, not the robot's: family conversations about privacy with social robots in the home.",
    "Do Privacy Concerns About Social Robots Affect Use Intentions? Evidence From an Experimental Vignette Study.",
    "What should a robot disclose about me? A study about privacy-appropriate behaviors for social robots.",
    "Privacy framework for context-aware robot development.",
    "User expectations of privacy in robot assisted therapy.",
    "Toward privacy-sensitive human-robot interaction: Privacy terms and human-data interaction in the personal robot era.",
    "\"I still need my privacy\": Exploring the level of comfort and privacy preferences of German-speaking older adults in the case of mobile assistant robots.",
    "Editorial: Privacy-preserving deep heterogeneous view perception for data learning in neurorobotics volume II.",
    "Robot location privacy protection based on Q-learning particle swarm optimization algorithm in mobile crowdsensing.",
    "Comparative legal study on privacy and personal data protection for robots equipped with artificial intelligence: looking at functional and technological aspects.",
    "Bringing older people's perspectives on consumer socially assistive robots into debates about the future of privacy protection and AI governance.",
    "\"Yes, It's Cute, But How Can I Be Sure It's Safe or Not?\" Investigating the Intention to Use Service Robots in the Context of Privacy Calculus.",
    "Verbal anthropomorphism design of social robots: Investigating users' privacy perception.",
    "Privacy-preserving image multi-classification deep learning model in robot system of industrial IoT.",
    "PrivShieldROS: An Extended Robot Operating System Integrating Ethereum and Interplanetary File System for Enhanced Sensor Data Privacy.",
    "Privacy beyond Data: Assessment and Mitigation of Privacy Risks in Robotic Technology for Elderly Care.",
    "Swarm Robotic Flocking With Aggregation Ability Privacy.",
    "Let us make robots \"Think in child!\": How children conceptualize fairness, inclusion, and privacy with social robots.",
    "Visual privacy behaviour recognition for social robots based on an improved generative adversarial network.",
    "Using an autonomous robot to maintain privacy in assistive environments.",
    "\"I spy, with my little sensor\": fair data handling practices for robots between privacy, copyright and security.",
    "PDLHR: Privacy-Preserving Deep Learning Model With Homomorphic Re-Encryption in Robot System.",
    "Securing the Internet of Robotic Things (IoRT) against DDoS Attacks: A Federated Learning with Differential Privacy Clustering Approach.",
    "FedHIP: Federated learning for privacy-preserving human intention prediction in human-robot collaborative assembly tasks.",
    "Security and privacy of network transmitted system in the Internet of Robotic Things.",
    "Correction to: Loss-based differentiation strategy for privacy preserving of social robots.",
    "Loss-based differentiation strategy for privacy preserving of social robots.",
    "Building a speech recognition system with privacy identification information based on Google Voice for social robots.",
    "Privacy-preserving data integration scheme in industrial robot system based on fog computing and edge computing.",
    "EPDB: An Efficient and Privacy-Preserving Electric Charging Scheme in Internet of Robotic Things.",
    "Privacy-Preserving Synthetic Continual Semantic Segmentation for Robotic Surgery.",
    "Thermal Imaging in Robotics as a Privacy-Enhancing or Privacy-Invasive Measure? Misconceptions of Privacy when Using Thermal Cameras in Robots.",
    "Robots in the cloud with privacy: A new threat to data protection?",
    "Privacy-preserving dynamic average consensus via state decomposition: Case study on multi-robot formation control.",
    "Decentralized P2P Federated Learning for Privacy-Preserving and Resilient Mobile Robotic Systems.",
    "A Survey on Privacy Attacks Against Digital Twin Systems in AI-Robotics.",
    "Privacy-Preserving Pose Estimation for Human-Robot Interaction.",
    "Privacy with Surgical Robotics: Challenges in Applying Contextual Privacy Theory.",
    "BRNES: Enabling Security and Privacy-aware Experience Sharing in Multiagent Robotic and Autonomous Systems.",
    "A Taxonomy of Privacy Constructs for Privacy-Sensitive Robotics.",
    "Customer Empowered Privacy-Preserving Secure Verification using Decentralized Identifier and Verifiable Credentials For Product Delivery Using Robots.",
    "Privacy at Home: an Inquiry into Sensors and Robots for the Stay at Home Elderly.",
    "Federated Imitation Learning: A Privacy Considered Imitation Learning Framework for Cloud Robotic Systems with Heterogeneous Sensor Data.",
    "Privacy Risks of Robot Vision: A User Study on Image Modalities and Resolution.",
    "Privacy-preserving Robotic-based Multi-factor Authentication Scheme for Secure Automated Delivery System.",
    "Decentralized Robot Learning for Personalization and Privacy.",
    "Towards Privacy-Aware and Personalised Assistive Robots: A User-Centred Approach.",
    "Framing Effects on Privacy Concerns about a Home Telepresence Robot.",
    "Investigating the Privacy Risk of Using Robot Vacuum Cleaners in Smart Environments.",
    "Designing Commercial Therapeutic Robots for Privacy Preserving Systems and Ethical Research Practices within the Home.",
    "Robots as AI Double Agents: Privacy in Motion Planning.",
    "Privacy-Preserving Synthetic Continual Semantic Segmentation for Robotic Surgery.",
    "CONFIDANT: A Privacy Controller for Social Robots.",
    "RoboComm: A DID-based scalable and privacy-preserving Robot-to-Robot interaction over state channels.",
    "PANav: Toward Privacy-Aware Robot Navigation via Vision-Language Models.",
    "Real-Time Privacy Preservation for Robot Visual Perception.",
    "Privacy-Preserving Dynamic Average Consensus via State Decomposition: Case Study on Multi-Robot Formation Control.",
    "A Macroscopic Model for Differential Privacy in Dynamic Robotic Networks.",
    "Federated Deep Reinforcement Learning for Privacy-Preserving Robotic-Assisted Surgery.",
    "Securing the Future: Exploring Privacy Risks and Security Questions in Robotic Systems.",
    "Cloud Computing Architecture Based on Network Security Vulnerabilities and Privacy Protection in the Kinematic Model of Hybrid Robots."
}

sarah_search = {
    "Thermal Imaging in Robotics as a Privacy-Enhancing or Privacy-Invasive Measure? Misconceptions of Privacy when Using Thermal Cameras in Robots.",
    "Toward privacy-sensitive human-robot interaction: Privacy terms and human-data interaction in the personal robot era.",
    "Is the Robot Spying on me? A Study on Perceived Privacy in Telepresence Scenarios in a Care Setting with Mobile and Humanoid Robots.",
    "Privacy beyond Data: Assessment and Mitigation of Privacy Risks in Robotic Technology for Elderly Care.",
    "Our business, not the robot's: family conversations about privacy with social robots in the home.",
    "\"Socially Assistive Robot Privacy Model\": A Multi-model Approach to Evaluating Socially Assistive Robot Privacy Concerns.",
    "What should a robot disclose about me? A study about privacy-appropriate behaviors for social robots.",
    "Never Trust Anything That Can Think for Itself, if You Can't Control Its Privacy Settings: The Influence of a Robot's Privacy Settings on Users' Attitudes and Willingness to Self-disclose.",
    "Law of the Robot: EU Law on Privacy in Human-Robot Interaction: Misconceptions, Fragmentations and Complexities.",
    "Let us make robots \"Think in child!\": How children conceptualize fairness, inclusion, and privacy with social robots.",
    "Effects of Privacy Warning on the Intention to Disclose Personal Information During Interaction with a Robot in Public Spaces.",
    "RoboComm: A DID-based scalable and privacy-preserving Robot-to-Robot interaction over state channels.",
    "A Qualitative Observational Video-Based Study on Perceived Privacy in Social Robots' Based on Robots Appearances.",
    "Privacy-Secure HRI: Framework of Human-Robot Interaction Protecting User's Privacy.",
    "Navigating the Human-Robot Interaction Landscape. Practical Guidelines for Privacy-Conscious Social Robots.",
    "Your Robot Might Be Inadvertently or Deliberately Spying on You: A Critical Analysis of Privacy Practices in the Robotics Industry.",
    "Exploring Privacy Concerns, Privacy Risks and Benefits on Users' Trust and Engagement in Continual Use of Service Robots.",
    "Effects of Social Behaviors of Robots in Privacy-Sensitive Situations.",
    "Tolerating Untrustworthy Robots: Studying Human Vulnerability Experience within a Privacy Scenario for Trust in Robots.",
    "Do Privacy Concerns About Social Robots Affect Use Intentions? Evidence From an Experimental Vignette Study.",
    "Privacy framework for context-aware robot development.",
    "\"I still need my privacy\": Exploring the level of comfort and privacy preferences of German-speaking older adults in the case of mobile assistant robots.",
    "Towards Designing Privacy-Compliant Social Robots for Use in Private Households: A Use Case Based Identification of Privacy Implications and Potential Technical Measures for Mitigation.",
    "User expectations of privacy in robot assisted therapy.",
    "Privacy with Surgical Robotics: Challenges in Applying Contextual Privacy Theory.",
    "Walking Away from the Robot: Negotiating Privacy with a Robot.",
    "Privacy and Socially Assistive Robots - A Meta Study.",
    "A Taxonomy of Privacy Constructs for Privacy-Sensitive Robotics.",
    "Designing Commercial Therapeutic Robots for Privacy Preserving Systems and Ethical Research Practices Within the Home.",
    "The Robot Who Knew Too Much: Toward Understanding the Privacy/Personalization Trade-Off in Child-Robot Conversation.",
    "Robotic Society: Privacy as a Legal and Technological Issue.",
    "Influence of the Privacy Issue in the Deployment and Design of Networking Robots in European Urban Areas.",
    "Bringing older people's perspectives on consumer socially assistive robots into debates about the future of privacy protection and AI governance.",
    "Securing the Internet of Robotic Things (IoRT) against DDoS Attacks: A Federated Learning with Differential Privacy Clustering Approach.",
    "Privacy Preserving Federated Reinforcement Imitation Learning Framework With Robust Aggregation for Cloud-Based Domestic Robots.",
    "Exploring the Impact of Social Robot Design Characteristics on Users' Privacy Concerns: Evidence from PLS-SEM and FsQCA.",
    "Cloud Computing Architecture Based on Network Security Vulnerabilities and Privacy Protection in the Kinematic Model of Hybrid Robots.",
    "Swarm Robotic Flocking With Aggregation Ability Privacy.",
    "Analyzing Security & Privacy (S&P) Labels For AI Integrated Social Robots: A Novel User Assessment Based Research Study.",
    "Privacy-Sensitive Robotics: Perceptions, Measures, and Metrics.",
    "Contextual Understanding of Teen & Youth Privacy Perceptions with Social Robots.",
    "Effective Engineering, Stakeholder Involvement, and Regulatory Plurality Within Privacy-Aware Robotics.",
    "Protecting User Data Through Privacy-Sensitive Robot Design.",
    "Understanding Worker Perceptions Toward Privacy When Working with Collaborative Robots That Provide As-Needed Assistance.",
    "Towards A Unique User-Centric Security & Privacy (S&P) Label For Social Robots.",
    "Real-Time Privacy Preservation for Robot Visual Perception.",
    "Privacy Risks of Robot Vision: A User Study on Image Modalities and Resolution.",
    "Federated Deep Reinforcement Learning for Privacy-Preserving Robotic-Assisted Surgery.",
    "Advancing Safety and Privacy in Human-Robot Interaction: Exploring Learning-Based Control and Multi-Modal Sensing Approaches.",
    "FedHIP: Federated learning for privacy-preserving human intention prediction in human-robot collaborative assembly tasks.",
    "Privacy-preserving data integration scheme in industrial robot system based on fog computing and edge computing.",
    "Visual privacy behaviour recognition for social robots based on an improved generative adversarial network.",
    "\"Yes, It's Cute, But How Can I Be Sure It's Safe or Not?\" Investigating the Intention to Use Service Robots in the Context of Privacy Calculus.",
    "EPDB: An Efficient and Privacy-Preserving Electric Charging Scheme in Internet of Robotic Things.",
    "Usage Intention of Social Robots for Domestic Purpose: From Security, Privacy, and Legal Perspectives.",
    "Data Privacy Preserving for Centralized Robotic Fault Diagnosis With Modified Dataset Distillation.",
    "Survey of Recent Results in Privacy-Preserving Mechanisms for Multi-Agent Systems.",
    "Privacy's Sky-High Battle: The Use of Unmanned Aircraft Systems for Law Enforcement in the European Union.",
    "Privacy-preserving federated transfer learning for defect identification from highly imbalanced image data in additive manufacturing.",
    "PrivShieldROS: An Extended Robot Operating System Integrating Ethereum and Interplanetary File System for Enhanced Sensor Data Privacy.",
    "Privacy-Preserving Synthetic Continual Semantic Segmentation for Robotic Surgery.",
    "Investigating Limits and Effectiveness of Privacy Conversations: the Case of Service Robots in an Office Environment.",
    "A Survey on Privacy Attacks Against Digital Twin Systems in AI-Robotics.",
    "Navigating Privacy Patterns in the Era of Robotaxis.",
    "PriMA-Care: Privacy-Preserving Multi-modal Dataset for Human Activity Recognition in Care Robots.",
    "Social Robots in Healthcare: Characterizing Privacy Considerations.",
    "Surveying Adult Perceptions of Privacy and Attitudes towards Social Robots in the Home.",
    "Privacy Aware Robotics.",
    "Snitches Get Unplugged: Adolescents' Privacy Concerns about Robots in the Home are Relationally Situated.",
    "Investigating the Privacy Risk of Using Robot Vacuum Cleaners in Smart Environments.",
    "Beyond Data Collection: Safeguarding User Privacy in Social Robotics.",
    "Privacy Risks in Reinforcement Learning for Household Robots.",
    "Towards Privacy-friendly Telepresence Robots for Schoolchildren with Long-term Illnesses - User Needs of Relevant User Groups.",
    "\"I Don't Want Parents to Watch My Lessons\" - Privacy Trade-offs in the Use of Telepresence Robots in Schools for Children with Long-term Illnesses.",
    "Examining Diverse Gender Dynamics in Human-Robot Interaction: Trust Privacy and Safety Perceptions.",
    "Comparative Analysis of Vision-Based Sensors for Human Monitoring in Care Robots: Exploring the Utility-Privacy Trade-off.",
    "Investigating Privacy in the Context of Office Delivery Robots.",
    "Performing Human Shadow Detection for Camera-Based Privacy-Preserving Human-Robot Interactions.",
    "Privacy Communication Patterns for Domestic Robots.",
    "Privacy-Preserving Synthetic Continual Semantic Segmentation for Robotic Surgery.",
    "Towards Privacy-Aware and Personalised Assistive Robots: A User-Centred Approach.",
    "A Survey on Privacy Attacks Against Digital Twin Systems in AI-Robotics.",
    "Investigating the Privacy Risk of Using Robot Vacuum Cleaners in Smart Environments.",
    "Securing the Future: Exploring Privacy Risks and Security Questions in Robotic Systems.",
    "PANav: Toward Privacy-Aware Robot Navigation via Vision-Language Models.",
    "Privacy-preserving Robotic-based Multi-factor Authentication Scheme for Secure Automated Delivery System.",
    "Verbal anthropomorphism design of social robots: Investigating users' privacy perception.",
    "Automatic Detection of Out-of-Body Frames in Surgical Videos for Privacy Protection Using Self-Supervised Learning and Minimal Labels.",
    "Loss-based differentiation strategy for privacy preserving of social robots.",
    "Correction to: Loss-based differentiation strategy for privacy preserving of social robots.",
    "Decentralized P2P Federated Learning for Privacy-Preserving and Resilient Mobile Robotic Systems.",
    "Privacy-Preserving User Pose Prediction for Safe and Efficient Human-Robot Interaction.",
    "Designing for In-Home Long-Term Family-Robot Interactions: Family Preferences, Connection-Making, and Privacy.",
    "Co-Learning around Social Robots with School Pupils and University Students - Focus on Data Privacy Considerations.",
    "Understanding Privacy-friendly Design of Robot Eyes.",
    "Obscuring Objectives with Pareto-Optimal Privacy-Aware Trajectories in Multi-Robot Coverage.",
    "Demo: Privacy-Preserving Localization for Edge-Assisted Robotic Navigation.",
    "Social Robots in Care and Data Privacy - A European Perspective.",
    "BRNES: Enabling Security and Privacy-Aware Experience Sharing in Multiagent Robotic and Autonomous Systems.",
    "Robots as AI Double Agents: Privacy in Motion Planning.",
    "Evaluating People's Perception of Trust and Privacy based on Robot's Appearance.",
    "Ethical Design for Privacy-related Communication in Human-Robot Interaction.",
    "Securing the Future: Exploring Privacy Risks and Security Questions in Robotic Systems.",
    "BRNES: Enabling Security and Privacy-aware Experience Sharing in Multiagent Robotic and Autonomous Systems.",
    "Robots as AI Double Agents: Privacy in Motion Planning.",
    "Privacy-preserving dynamic average consensus via state decomposition: Case study on multi-robot formation control.",
    "Robot location privacy protection based on Q-learning particle swarm optimization algorithm in mobile crowdsensing.",
    "Agree to Disagree: Subjective Fairness in Privacy-Restricted Decentralised Conflict Resolution.",
    "Drones, Real Estate Video Surveillance, and Neighbourhood Right to Privacy - The Potential Area of Normative Impact from the Perspective of the Polish Law.",
    "PDLHR: Privacy-Preserving Deep Learning Model With Homomorphic Re-Encryption in Robot System.",
    "Security and privacy of network transmitted system in the Internet of Robotic Things.",
    "Building a speech recognition system with privacy identification information based on Google Voice for social robots.",
    "Consumer-Friendly Methods for Privacy Protection Against Cleaning Robots.",
    "Privacy and security challenges for autonomous agents : A study of two social humanoid service robots.",
    "Privacy-Preserving Multi-Robot Task Allocation via Secure Multi-Party Computation.",
    "CONFIDANT: A Privacy Controller for Social Robots.",
    "AI privacy preserving robots working in a smart sensor environment.",
    "Public Perception, Privacy, Safety, and Ethical Considerations of Communication Robots in Law Enforcement.",
    "Called Back Onstage: Dramaturgic Analysis, Domestic Social Robots, and Privacy.",
    "Privacy and Security Concerns in Edge Computing-Based Smart Cities.",
    "CONFIDANT: A Privacy Controller for Social Robots.",
    "Decentralized Robot Learning for Personalization and Privacy.",
    "Customer Empowered Privacy-Preserving Secure Verification using Decentralized Identifier and Verifiable Credentials For Product Delivery Using Robots.",
    "Privacy-preserving image multi-classification deep learning model in robot system of industrial IoT.",
    "Are You Watching Me? A Study on Privacy Notice Design of Social Robot.",
    "Privacy Behavior of the Elderly toward Caregiver Robots.",
    "\"They See You're a Girl if You Pick a Pink Robot with a Skirt\": A Qualitative Study of How Children Conceptualize Data Processing and Digital Privacy Risks.",
    "Designing and Validating a Blockchain-based Architecture to Enforce Privacy in Human Robot Interaction.",
    "Privacy-Preserving and Auditable Federated Deep Reinforcement Learning for Robotic Manipulation.",
    "Designing a System Based on Robotic Assistance for Privacy Awareness in Smart Environments.",
    "Towards Privacy-Preserving Ego-Motion Estimation Using an Extremely Low-Resolution Camera.",
    "BlockRobot: Increasing Privacy in Human Robot Interaction by Using Blockchain.",
    "How do People Perceive Privacy and Interaction Quality while Chatting with a Crowd-operated Robot?",
    "Enhancing Privacy in Robotics via Judicious Sensor Selection.",
    "Artificial Empathy for Clinical Companion Robots with Privacy-By-Design.",
    "Do Privacy Concerns Prevent Employees' Acceptance of Smart Wearables and Collaborative Robots?",
    "A Privacy Filter Framework for Internet of Robotic Things Applications.",
    "Privacy at Home: an Inquiry into Sensors and Robots for the Stay at Home Elderly.",
    "Privacy-Preserving Dynamic Average Consensus via State Decomposition: Case Study on Multi-Robot Formation Control.",
    "Privacy-Preserving Pose Estimation for Human-Robot Interaction.",
    "Comparative legal study on privacy and personal data protection for robots equipped with artificial intelligence: looking at functional and technological aspects.",
    "Complete characterization of a class of privacy-preserving tracking problems.",
    "Trust-Driven Privacy in Human-Robot Interactions.",
    "Coordinated multi-robot planning while preserving individual privacy.",
    "Privacy-Preserving Robot Vision with Anonymized Faces by Extreme Low Resolution.",
    "Privacy First: Designing Responsible and Inclusive Social Robot Applications for in the Wild Studies.",
    "Privacy Concerns in Robot Teleoperation: Does Personality Influence What Should Be Hidden?",
    "ROS-Defender: SDN-Based Security Policy Enforcement for Robotic Applications.",
    "Resilience of Multi-robot Systems to Physical Masquerade Attacks.",
    "Federated Imitation Learning: A Privacy Considered Imitation Learning Framework for Cloud Robotic Systems with Heterogeneous Sensor Data.",
    "Framing Effects on Privacy Concerns about a Home Telepresence Robot.",
    "Privacy in Control and Dynamical Systems.",
    "Themes and Research Directions in Privacy-Sensitive Robotics.",
    "Privacy at Home: An Inquiry into Sensors and Robots for the Stay at Home Elderly.",
    "Be More Transparent and Users Will Like You: A Robot Privacy and User Experience Design Experiment.",
    "Me and My Robot - Sharing Information with a New Friend.",
    "\"I spy, with my little sensor\": fair data handling practices for robots between privacy, copyright and security.",
    "Distributed mapping with privacy and communication constraints: Lightweight algorithms and object-based models.",
    "Information Security, Privacy, and Trust in Social Robotic Assistants for Older Adults.",
    "Privacy and Telepresence Robotics: What do Non-scientists Think?",
    "Framing Effects on Privacy Concerns about a Home Telepresence Robot.",
    "Privacy-Sensitive Robotics.",
    "From the Glass House to the Hive: The Private Sphere in the Era of Intelligent Home Assistant Robots.",
    "A focus group study of privacy concerns about telepresence robots.",
    "A Telepresence Robot in Residential Care: Family Increasingly Present, Personnel Worried About Privacy.",
    "Embodiment, Privacy and Social Robots: May I Remember You?",
    "An Experimental Security Analysis of an Industrial Robot Controller.",
    "A Macroscopic Model for Differential Privacy in Dynamic Robotic Networks.",
    "These aren't the autonomous drones you're looking for: investigating privacy concerns through concept videos.",
    "A Macroscopic Privacy Model for Heterogeneous Robot Swarms.",
    "Detection of privacy-sensitive situations for social robots in smart homes.",
    "User Feedback on Physical Marker Interfaces for Protecting Visual Privacy from Mobile Robots.",
    "Evaluation of physical marker interfaces for protecting visual privacy from mobile robots.",
    "Social Robots, Privacy, and Ownership of Data: Some Problems and Suggestions.",
    "Designing Commercial Therapeutic Robots for Privacy Preserving Systems and Ethical Research Practices within the Home.",
    "Neural network-based ideation learning for intelligent agents: e-brainstorming with privacy preferences.",
    "The Privacy-Utility Tradeoff for Remotely Teleoperated Robots.",
    "RoboCode-Ethicists: Privacy-friendly robots, an ethical responsibility of engineers?",
    "RoboCode-Ethicists: Privacy-friendly robots, an ethical responsibility of engineers?",
    "Morphological gender recognition by a social robot and privacy concerns: late breaking reports.",
    "Robots in the cloud with privacy: A new threat to data protection?",
    "The effect of monitoring by cameras and robots on the privacy enhancing behaviors of older adults.",
    "Issues of privacy and electronic personhood in robotics.",
    "Using an autonomous robot to maintain privacy in assistive environments.",
    "Understanding users' perception of privacy in human-robot interaction.",
    "A spotlight on security and privacy risks with future household robots: attacks and lessons."
}

different = sarah_search - my_search
print(different)
print(len(different))

different_1 = my_search - sarah_search
print(len(different_1))
print(different_1)